services:
  - type: web
    name: sistem-pengaduan
    runtime: docker
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: app.baseURL
        sync: false  # Set manually after first deploy
      - key: database.default.hostname
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: database.default.database
        value: db_sima_bapelkes
      - key: database.default.username
        value: 24tY5NLiHYD4iRL.root
      - key: database.default.password
        generateValue: false  # Set manually as a secret
      - key: database.default.DBDriver
        value: MySQLi
      - key: database.default.port
        value: "4000"
